/* Generated By:JJTree: Do not edit this line. ASTAbstractVariables.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTAbstractVariables extends SimpleNode {
  public ASTAbstractVariables(int id) {
    super(id);
  }

  public ASTAbstractVariables(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ffcf3587fe3ad36b5660527c3ae348ee (do not edit this line) */
