/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTArrayElement extends SimpleNode {
  public ASTArrayElement(int id) {
    super(id);
  }

  public ASTArrayElement(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3830e0b6b8b3519552cbe5ff36d807d2 (do not edit this line) */
