/* Generated By:JJTree: Do not edit this line. ASTAssertions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTAssertions extends SimpleNode {
  public ASTAssertions(int id) {
    super(id);
  }

  public ASTAssertions(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4809a13b0cbe73bf8e0eaae79aef2a9a (do not edit this line) */
