/* Generated By:JJTree: Do not edit this line. ASTAbstractConstants.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTAbstractConstants extends SimpleNode {
  public ASTAbstractConstants(int id) {
    super(id);
  }

  public ASTAbstractConstants(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=52ca9f92917b5c4193f5de3db8cf098e (do not edit this line) */
