/* Generated By:JJTree: Do not edit this line. ASTBooleanSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTBooleanSet extends SimpleNode {
  public ASTBooleanSet(int id) {
    super(id);
  }

  public ASTBooleanSet(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=869cc99a2d58b92f2261ec717b9b775a (do not edit this line) */
