/* Generated By:JJTree: Do not edit this line. ASTClosure1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTClosure1 extends SimpleNode {
  public ASTClosure1(int id) {
    super(id);
  }

  public ASTClosure1(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3bacc251d2da94c9da4d9163adee1005 (do not edit this line) */
