/* Generated By:JJTree: Do not edit this line. ASTClosure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTClosure extends SimpleNode {
  public ASTClosure(int id) {
    super(id);
  }

  public ASTClosure(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a1e00f769520ac6a7e47102551745992 (do not edit this line) */
