/* Generated By:JJTree: Do not edit this line. ASTConditionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTConditionExpression extends SimpleNode {
  public ASTConditionExpression(int id) {
    super(id);
  }

  public ASTConditionExpression(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01f9c128084a721907f90dc4f8bfb536 (do not edit this line) */
