/* Generated By:JJTree: Do not edit this line. ASTCallDefinitionListExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTCallDefinitionListExpression extends SimpleNode {
  public ASTCallDefinitionListExpression(int id) {
    super(id);
  }

  public ASTCallDefinitionListExpression(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e60b77faaa0c14252dc5bca2752a272 (do not edit this line) */
