/* Generated By:JJTree: Do not edit this line. ASTCard.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTCard extends SimpleNode {
  public ASTCard(int id) {
    super(id);
  }

  public ASTCard(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b9fe6be15dc1d4d34ddc0cee426e2c24 (do not edit this line) */
