/* Generated By:JJTree: Do not edit this line. ASTConstraints.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTConstraints extends SimpleNode {
  public ASTConstraints(int id) {
    super(id);
  }

  public ASTConstraints(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d17a60813f67e5727d3866a5746d61a (do not edit this line) */
