/* Generated By:JJTree: Do not edit this line. ASTComprehensionSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTComprehensionSet extends SimpleNode {
  public ASTComprehensionSet(int id) {
    super(id);
  }

  public ASTComprehensionSet(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7c1449184d4890611b7d08fcc3e77d53 (do not edit this line) */
