/* Generated By:JJTree: Do not edit this line. ASTCallDefinitionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTCallDefinitionExpression extends SimpleNode {
  public ASTCallDefinitionExpression(int id) {
    super(id);
  }

  public ASTCallDefinitionExpression(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f41b2392c564cf9554bb4575b9953f2 (do not edit this line) */
