/* Generated By:JJTree: Do not edit this line. ASTCondition0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTCondition0 extends SimpleNode {
  public ASTCondition0(int id) {
    super(id);
  }

  public ASTCondition0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5958f900b2f40f81aff6e51cef0e425e (do not edit this line) */
