/* Generated By:JJTree: Do not edit this line. ASTConcreteConstants.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTConcreteConstants extends SimpleNode {
  public ASTConcreteConstants(int id) {
    super(id);
  }

  public ASTConcreteConstants(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=996022f0ad645a3a77f3bd2f42b56d04 (do not edit this line) */
