/* Generated By:JJTree: Do not edit this line. ASTConc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTConc extends SimpleNode {
  public ASTConc(int id) {
    super(id);
  }

  public ASTConc(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dfc3d81f2db785221dc486616977a33c (do not edit this line) */
