/* Generated By:JJTree: Do not edit this line. ASTCallInTerme.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTCallInTerme extends SimpleNode {
  public ASTCallInTerme(int id) {
    super(id);
  }

  public ASTCallInTerme(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=93178cfd26294a189960911449d6ad4a (do not edit this line) */
