/* Generated By:JJTree: Do not edit this line. ASTCallDefinitionSubstitution.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTCallDefinitionSubstitution extends SimpleNode {
  public ASTCallDefinitionSubstitution(int id) {
    super(id);
  }

  public ASTCallDefinitionSubstitution(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4fa2726bed935202b8c11cc8c693c38 (do not edit this line) */
