/* Generated By:JJTree: Do not edit this line. ASTCallFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTCallFunction extends SimpleNode {
  public ASTCallFunction(int id) {
    super(id);
  }

  public ASTCallFunction(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba8c9622d752fbc1006eff2565c06d8d (do not edit this line) */
