/* Generated By:JJTree: Do not edit this line. ASTDollarZero.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTDollarZero extends SimpleNode {
  public ASTDollarZero(int id) {
    super(id);
  }

  public ASTDollarZero(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=336d5358c3d697247120b097a49a494f (do not edit this line) */
