/* Generated By:JJTree: Do not edit this line. ASTDomain.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTDomain extends SimpleNode {
  public ASTDomain(int id) {
    super(id);
  }

  public ASTDomain(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=71a2310f815626980b725238a4470a90 (do not edit this line) */
