/* Generated By:JJTree: Do not edit this line. ASTDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTDefinition extends SimpleNode {
  public ASTDefinition(int id) {
    super(id);
  }

  public ASTDefinition(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b2bb740dc351f48f3c905d5ddd42d58a (do not edit this line) */
