/* Generated By:JJTree: Do not edit this line. ASTDefinitions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTDefinitions extends SimpleNode {
  public ASTDefinitions(int id) {
    super(id);
  }

  public ASTDefinitions(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2c72307982d36e10e0872535a1987785 (do not edit this line) */
