/* Generated By:JJTree: Do not edit this line. ASTEmptySet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTEmptySet extends SimpleNode {
  public ASTEmptySet(int id) {
    super(id);
  }

  public ASTEmptySet(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f26404751fd06b52f30c92d099789cc5 (do not edit this line) */
