/* Generated By:JJTree: Do not edit this line. ASTEmptySequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTEmptySequence extends SimpleNode {
  public ASTEmptySequence(int id) {
    super(id);
  }

  public ASTEmptySequence(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c07f06f4b354c2fbaf8fa379f386e569 (do not edit this line) */
