/* Generated By:JJTree: Do not edit this line. ASTExists.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExists extends SimpleNode {
  public ASTExists(int id) {
    super(id);
  }

  public ASTExists(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=42e84281f9f3c585c4f5072b069c83ba (do not edit this line) */
