/* Generated By:JJTree: Do not edit this line. ASTExprArith2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExprArith2 extends SimpleNode {
  public ASTExprArith2(int id) {
    super(id);
  }

  public ASTExprArith2(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75ed1bc068a097d8620a1c4f465fe85d (do not edit this line) */
