/* Generated By:JJTree: Do not edit this line. ASTElseIf.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTElseIf extends SimpleNode {
  public ASTElseIf(int id) {
    super(id);
  }

  public ASTElseIf(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f78ead9660fa71fcee0f241b7bdba1ba (do not edit this line) */
