/* Generated By:JJTree: Do not edit this line. ASTExpr2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExpr2 extends SimpleNode {
  public ASTExpr2(int id) {
    super(id);
  }

  public ASTExpr2(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=07905dc53ccb1e008310cb052ab85158 (do not edit this line) */
