/* Generated By:JJTree: Do not edit this line. ASTExprArith.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExprArith extends SimpleNode {
  public ASTExprArith(int id) {
    super(id);
  }

  public ASTExprArith(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=25f71369f12dce6e0cfc4f53f471e692 (do not edit this line) */
