/* Generated By:JJTree: Do not edit this line. ASTExpr4.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExpr4 extends SimpleNode {
  public ASTExpr4(int id) {
    super(id);
  }

  public ASTExpr4(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58010e107310160b695e6ad8831ff850 (do not edit this line) */
