/* Generated By:JJTree: Do not edit this line. ASTExpr0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExpr0 extends SimpleNode {
  public ASTExpr0(int id) {
    super(id);
  }

  public ASTExpr0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=495c2ef702d12947f0e8f57e01dd61dd (do not edit this line) */
