/* Generated By:JJTree: Do not edit this line. ASTExpr6.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExpr6 extends SimpleNode {
  public ASTExpr6(int id) {
    super(id);
  }

  public ASTExpr6(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e627a81931192db6bf12bc03d3c38227 (do not edit this line) */
