/* Generated By:JJTree: Do not edit this line. ASTExpr7.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExpr7 extends SimpleNode {
  public ASTExpr7(int id) {
    super(id);
  }

  public ASTExpr7(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=97ef35857bdbfdffcb5da64b8f606b12 (do not edit this line) */
