/* Generated By:JJTree: Do not edit this line. ASTExprArith1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExprArith1 extends SimpleNode {
  public ASTExprArith1(int id) {
    super(id);
  }

  public ASTExprArith1(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff8d01a8572b884af5095d9be70decc2 (do not edit this line) */
