/* Generated By:JJTree: Do not edit this line. ASTExprArith0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExprArith0 extends SimpleNode {
  public ASTExprArith0(int id) {
    super(id);
  }

  public ASTExprArith0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=930f88a05077229cd260d6ad49ec8fbf (do not edit this line) */
