/* Generated By:JJTree: Do not edit this line. ASTEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTEqual extends SimpleNode {
  public ASTEqual(int id) {
    super(id);
  }

  public ASTEqual(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ff1e7b44c72c2fa678c32dbea8068c5 (do not edit this line) */
