/* Generated By:JJTree: Do not edit this line. ASTExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExpr extends SimpleNode {
  public ASTExpr(int id) {
    super(id);
  }

  public ASTExpr(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=20666442b0d75517430d54178381847e (do not edit this line) */
