/* Generated By:JJTree: Do not edit this line. ASTElse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTElse extends SimpleNode {
  public ASTElse(int id) {
    super(id);
  }

  public ASTElse(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3633d232ae193b6daccfc11dbab0033c (do not edit this line) */
