/* Generated By:JJTree: Do not edit this line. ASTExpr5.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExpr5 extends SimpleNode {
  public ASTExpr5(int id) {
    super(id);
  }

  public ASTExpr5(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=41c26ca7cc50b524d158ce232d07b0bf (do not edit this line) */
