/* Generated By:JJTree: Do not edit this line. ASTExtensionSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExtensionSet extends SimpleNode {
  public ASTExtensionSet(int id) {
    super(id);
  }

  public ASTExtensionSet(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57eb1e98f19d526ff0db51dc7da031d5 (do not edit this line) */
