/* Generated By:JJTree: Do not edit this line. ASTExtensionSequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExtensionSequence extends SimpleNode {
  public ASTExtensionSequence(int id) {
    super(id);
  }

  public ASTExtensionSequence(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3fa2ce4f450db839fddd9292b39ff0a (do not edit this line) */
