/* Generated By:JJTree: Do not edit this line. ASTElementUnionSetImplementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTElementUnionSetImplementation extends SimpleNode {
  public ASTElementUnionSetImplementation(int id) {
    super(id);
  }

  public ASTElementUnionSetImplementation(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5efcfcd5bc99713a0253d94ffbdbbc7 (do not edit this line) */
