/* Generated By:JJTree: Do not edit this line. ASTExpressionParenthesis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExpressionParenthesis extends SimpleNode {
  public ASTExpressionParenthesis(int id) {
    super(id);
  }

  public ASTExpressionParenthesis(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4c219d6fa85d1064870b50fec4c8eadc (do not edit this line) */
