/* Generated By:JJTree: Do not edit this line. ASTElementImplementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTElementImplementation extends SimpleNode {
  public ASTElementImplementation(int id) {
    super(id);
  }

  public ASTElementImplementation(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db2cfc6025d8be30d670a89eb87fe42f (do not edit this line) */
