/* Generated By:JJTree: Do not edit this line. ASTEither.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTEither extends SimpleNode {
  public ASTEither(int id) {
    super(id);
  }

  public ASTEither(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c92f8b3014a9bffd402e394d5058817 (do not edit this line) */
