/* Generated By:JJTree: Do not edit this line. ASTExpr3.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTExpr3 extends SimpleNode {
  public ASTExpr3(int id) {
    super(id);
  }

  public ASTExpr3(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4a40f1ec55ab262c789a0a9965d3c47 (do not edit this line) */
