/* Generated By:JJTree: Do not edit this line. ASTFront.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTFront extends SimpleNode {
  public ASTFront(int id) {
    super(id);
  }

  public ASTFront(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8bb63ea6e448bcf88e89e87ff337e9d8 (do not edit this line) */
