/* Generated By:JJTree: Do not edit this line. ASTForAll.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTForAll extends SimpleNode {
  public ASTForAll(int id) {
    super(id);
  }

  public ASTForAll(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5e8c6edc502b29cf4a824c968bf568a4 (do not edit this line) */
