/* Generated By:JJTree: Do not edit this line. ASTFinitePowerSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTFinitePowerSet extends SimpleNode {
  public ASTFinitePowerSet(int id) {
    super(id);
  }

  public ASTFinitePowerSet(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5f6e4308ea4ee01427c8182036c3073 (do not edit this line) */
