/* Generated By:JJTree: Do not edit this line. ASTFirst.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTFirst extends SimpleNode {
  public ASTFirst(int id) {
    super(id);
  }

  public ASTFirst(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ecfb370286c30f4e70011e0c612fd808 (do not edit this line) */
