/* Generated By:JJTree: Do not edit this line. ASTFnc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTFnc extends SimpleNode {
  public ASTFnc(int id) {
    super(id);
  }

  public ASTFnc(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60b04aeb0c0b947c6fd01202abe2bdcc (do not edit this line) */
