/* Generated By:JJTree: Do not edit this line. ASTHeader.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTHeader extends SimpleNode {
  public ASTHeader(int id) {
    super(id);
  }

  public ASTHeader(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d3383c9ae9c6f1e345a0ec7e77c89b0 (do not edit this line) */
