/* Generated By:JJTree: Do not edit this line. ASTImage.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTImage extends SimpleNode {
  public ASTImage(int id) {
    super(id);
  }

  public ASTImage(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f1558ecdcb19f9288848e186cf346c3 (do not edit this line) */
