/* Generated By:JJTree: Do not edit this line. ASTImports.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTImports extends SimpleNode {
  public ASTImports(int id) {
    super(id);
  }

  public ASTImports(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f84a2f5d9ce551a1c529bee843bb2862 (do not edit this line) */
