/* Generated By:JJTree: Do not edit this line. ASTIseq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTIseq extends SimpleNode {
  public ASTIseq(int id) {
    super(id);
  }

  public ASTIseq(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=11d333e30b6e36adf507586ea390facd (do not edit this line) */
