/* Generated By:JJTree: Do not edit this line. ASTIntersectionQuantified.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTIntersectionQuantified extends SimpleNode {
  public ASTIntersectionQuantified(int id) {
    super(id);
  }

  public ASTIntersectionQuantified(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5690d3fa1a1027abee9d55db545ec18 (do not edit this line) */
