/* Generated By:JJTree: Do not edit this line. ASTInverse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTInverse extends SimpleNode {
  public ASTInverse(int id) {
    super(id);
  }

  public ASTInverse(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8152e47186413351da8731ffede4c6d5 (do not edit this line) */
