/* Generated By:JJTree: Do not edit this line. ASTIterate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTIterate extends SimpleNode {
  public ASTIterate(int id) {
    super(id);
  }

  public ASTIterate(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=934579eb195b65f4447e3f97b5d2d69d (do not edit this line) */
