/* Generated By:JJTree: Do not edit this line. ASTIntegerSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTIntegerSet extends SimpleNode {
  public ASTIntegerSet(int id) {
    super(id);
  }

  public ASTIntegerSet(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0500bfe7dad5e489f5421d99c86ce0d8 (do not edit this line) */
