/* Generated By:JJTree: Do not edit this line. ASTInvariant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTInvariant extends SimpleNode {
  public ASTInvariant(int id) {
    super(id);
  }

  public ASTInvariant(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0829b033c66fea9d908ffd6bcb437a9d (do not edit this line) */
