/* Generated By:JJTree: Do not edit this line. ASTIntersectionGeneralized.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTIntersectionGeneralized extends SimpleNode {
  public ASTIntersectionGeneralized(int id) {
    super(id);
  }

  public ASTIntersectionGeneralized(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f007f66c92b72562203443268eedef6 (do not edit this line) */
