/* Generated By:JJTree: Do not edit this line. ASTIdentifiers.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTIdentifiers extends SimpleNode {
  public ASTIdentifiers(int id) {
    super(id);
  }

  public ASTIdentifiers(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c035f910af8336e268d09be69ccd0ce (do not edit this line) */
