/* Generated By:JJTree: Do not edit this line. ASTIncludes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTIncludes extends SimpleNode {
  public ASTIncludes(int id) {
    super(id);
  }

  public ASTIncludes(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=24ee2c58a5824bb92f67cd88a9d06bb7 (do not edit this line) */
