/* Generated By:JJTree: Do not edit this line. ASTInitialisation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTInitialisation extends SimpleNode {
  public ASTInitialisation(int id) {
    super(id);
  }

  public ASTInitialisation(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=419f99b1cc6e8b311a84d14ed4e160fe (do not edit this line) */
