/* Generated By:JJTree: Do not edit this line. ASTIdentity.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTIdentity extends SimpleNode {
  public ASTIdentity(int id) {
    super(id);
  }

  public ASTIdentity(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=04329a368914a33b7caa66337e706e54 (do not edit this line) */
