/* Generated By:JJTree: Do not edit this line. ASTImplication.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTImplication extends SimpleNode {
  public ASTImplication(int id) {
    super(id);
  }

  public ASTImplication(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49c4a2c2c231796ef87cca4b0abf3ce9 (do not edit this line) */
