/* Generated By:JJTree: Do not edit this line. ASTImplementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTImplementation extends SimpleNode {
  public ASTImplementation(int id) {
    super(id);
  }

  public ASTImplementation(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f438c7e72d0472b4b3b5c3ccb25b1267 (do not edit this line) */
