/* Generated By:JJTree: Do not edit this line. ASTIseq1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTIseq1 extends SimpleNode {
  public ASTIseq1(int id) {
    super(id);
  }

  public ASTIseq1(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de8c85979d23dd74f4cad2be97a8521c (do not edit this line) */
