/* Generated By:JJTree: Do not edit this line. ASTLambda.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTLambda extends SimpleNode {
  public ASTLambda(int id) {
    super(id);
  }

  public ASTLambda(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e472d1feb1cd99fc226b4e1c9aa34f6 (do not edit this line) */
