/* Generated By:JJTree: Do not edit this line. ASTLast.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTLast extends SimpleNode {
  public ASTLast(int id) {
    super(id);
  }

  public ASTLast(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4eea1ceaa21dae687eb25fafd31ad457 (do not edit this line) */
