/* Generated By:JJTree: Do not edit this line. ASTListIdent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTListIdent extends SimpleNode {
  public ASTListIdent(int id) {
    super(id);
  }

  public ASTListIdent(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=98dad819c7af96d5a6fec2989a27af69 (do not edit this line) */
