/* Generated By:JJTree: Do not edit this line. ASTListExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTListExpression extends SimpleNode {
  public ASTListExpression(int id) {
    super(id);
  }

  public ASTListExpression(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b7d4e771efd8f3069f6d0b2ee1352974 (do not edit this line) */
