/* Generated By:JJTree: Do not edit this line. ASTListeTermeString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTListeTermeString extends SimpleNode {
  public ASTListeTermeString(int id) {
    super(id);
  }

  public ASTListeTermeString(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ca2047d726975cc2f796ce04462da0c (do not edit this line) */
