/* Generated By:JJTree: Do not edit this line. ASTListParametresDefs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTListParametresDefs extends SimpleNode {
  public ASTListParametresDefs(int id) {
    super(id);
  }

  public ASTListParametresDefs(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=630fb1b9c7c48aedba39bbdd09e0ad98 (do not edit this line) */
