/* Generated By:JJTree: Do not edit this line. ASTLeftCallFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTLeftCallFunction extends SimpleNode {
  public ASTLeftCallFunction(int id) {
    super(id);
  }

  public ASTLeftCallFunction(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=36a3fdeddee496cf91e603940463d113 (do not edit this line) */
