/* Generated By:JJTree: Do not edit this line. ASTLetDefinitions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTLetDefinitions extends SimpleNode {
  public ASTLetDefinitions(int id) {
    super(id);
  }

  public ASTLetDefinitions(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d78fa13aae04d580e24bbecce82ea1b (do not edit this line) */
