/* Generated By:JJTree: Do not edit this line. ASTMin.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTMin extends SimpleNode {
  public ASTMin(int id) {
    super(id);
  }

  public ASTMin(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26663479d7dc630ead733889f1fdb818 (do not edit this line) */
