/* Generated By:JJTree: Do not edit this line. ASTMax.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTMax extends SimpleNode {
  public ASTMax(int id) {
    super(id);
  }

  public ASTMax(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5fd86bb8922df59ad0ae5e7c6285f430 (do not edit this line) */
