/* Generated By:JJTree: Do not edit this line. ASTMachine.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTMachine extends SimpleNode {
  public ASTMachine(int id) {
    super(id);
  }

  public ASTMachine(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b8e80f25a2e3724045999243cd90f39b (do not edit this line) */
