/* Generated By:JJTree: Do not edit this line. ASTNot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTNot extends SimpleNode {
  public ASTNot(int id) {
    super(id);
  }

  public ASTNot(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c623b10960d1976db7d5fdc4fc484fa (do not edit this line) */
