/* Generated By:JJTree: Do not edit this line. ASTNatRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTNatRange extends SimpleNode {
  public ASTNatRange(int id) {
    super(id);
  }

  public ASTNatRange(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aab7bdd10b111c326e8b3961372128ee (do not edit this line) */
