/* Generated By:JJTree: Do not edit this line. ASTNonEmptySubsets.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTNonEmptySubsets extends SimpleNode {
  public ASTNonEmptySubsets(int id) {
    super(id);
  }

  public ASTNonEmptySubsets(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75d56ecf263422a503c452a33d39ebb3 (do not edit this line) */
