/* Generated By:JJTree: Do not edit this line. ASTNonEmptyFiniteSubsets.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTNonEmptyFiniteSubsets extends SimpleNode {
  public ASTNonEmptyFiniteSubsets(int id) {
    super(id);
  }

  public ASTNonEmptyFiniteSubsets(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2dc3f5b51e3609f87bfaea409e2e58da (do not edit this line) */
