/* Generated By:JJTree: Do not edit this line. ASTOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTOperation extends SimpleNode {
  public ASTOperation(int id) {
    super(id);
  }

  public ASTOperation(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bbc1a925259bc7a9a4ee93158bc8222b (do not edit this line) */
