/* Generated By:JJTree: Do not edit this line. ASTOperations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTOperations extends SimpleNode {
  public ASTOperations(int id) {
    super(id);
  }

  public ASTOperations(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=38f8de37f21a90063f6b53aad47cc8ff (do not edit this line) */
