/* Generated By:JJTree: Do not edit this line. ASTPred.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPred extends SimpleNode {
  public ASTPred(int id) {
    super(id);
  }

  public ASTPred(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d67f2d18d4f427b0c6b5b50cc9b1819 (do not edit this line) */
