/* Generated By:JJTree: Do not edit this line. ASTPredLevel1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPredLevel1 extends SimpleNode {
  public ASTPredLevel1(int id) {
    super(id);
  }

  public ASTPredLevel1(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5bec97d44bdf60e57720ad014b86c30 (do not edit this line) */
