/* Generated By:JJTree: Do not edit this line. ASTPrj1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPrj1 extends SimpleNode {
  public ASTPrj1(int id) {
    super(id);
  }

  public ASTPrj1(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c70da819c82c6016781f890ac0be2de (do not edit this line) */
