/* Generated By:JJTree: Do not edit this line. ASTPerm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPerm extends SimpleNode {
  public ASTPerm(int id) {
    super(id);
  }

  public ASTPerm(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3a56f165bc064d194e400bf8ec515a0 (do not edit this line) */
