/* Generated By:JJTree: Do not edit this line. ASTProperties.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTProperties extends SimpleNode {
  public ASTProperties(int id) {
    super(id);
  }

  public ASTProperties(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5419dc784162a7b0f1b80a4ebcff440d (do not edit this line) */
