/* Generated By:JJTree: Do not edit this line. ASTPredicateParenthesis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPredicateParenthesis extends SimpleNode {
  public ASTPredicateParenthesis(int id) {
    super(id);
  }

  public ASTPredicateParenthesis(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=44357fc64ca0817f7bef0c88c81d17d3 (do not edit this line) */
