/* Generated By:JJTree: Do not edit this line. ASTPredLevel0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPredLevel0 extends SimpleNode {
  public ASTPredLevel0(int id) {
    super(id);
  }

  public ASTPredLevel0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eec5e628e558e56cea1363674d0ab349 (do not edit this line) */
