/* Generated By:JJTree: Do not edit this line. ASTParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTParameters extends SimpleNode {
  public ASTParameters(int id) {
    super(id);
  }

  public ASTParameters(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=53644d9fbf45d1094cca5ac74ef68ea0 (do not edit this line) */
