/* Generated By:JJTree: Do not edit this line. ASTPrj2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPrj2 extends SimpleNode {
  public ASTPrj2(int id) {
    super(id);
  }

  public ASTPrj2(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=530d47ff19b5085ca340039337fcdfcd (do not edit this line) */
