/* Generated By:JJTree: Do not edit this line. ASTPredicateExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPredicateExpression extends SimpleNode {
  public ASTPredicateExpression(int id) {
    super(id);
  }

  public ASTPredicateExpression(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dae45ea76e5e8b8a234217e74e9ef0a1 (do not edit this line) */
