/* Generated By:JJTree: Do not edit this line. ASTPowerSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPowerSet extends SimpleNode {
  public ASTPowerSet(int id) {
    super(id);
  }

  public ASTPowerSet(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=299753d87d41d9d0530ec9482401bab6 (do not edit this line) */
