/* Generated By:JJTree: Do not edit this line. ASTPi.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPi extends SimpleNode {
  public ASTPi(int id) {
    super(id);
  }

  public ASTPi(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bc55468b229cd4b4e5410c88d0d0a963 (do not edit this line) */
