/* Generated By:JJTree: Do not edit this line. ASTPredLevel3.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPredLevel3 extends SimpleNode {
  public ASTPredLevel3(int id) {
    super(id);
  }

  public ASTPredLevel3(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2bc5cd362fbb016a0f790d3a3476a11e (do not edit this line) */
