/* Generated By:JJTree: Do not edit this line. ASTPredLevel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTPredLevel extends SimpleNode {
  public ASTPredLevel(int id) {
    super(id);
  }

  public ASTPredLevel(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56beb1f1bf633df2606d3d8147932e8f (do not edit this line) */
