/* Generated By:JJTree: Do not edit this line. ASTRIndexOfElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRIndexOfElement extends SimpleNode {
  public ASTRIndexOfElement(int id) {
    super(id);
  }

  public ASTRIndexOfElement(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=143f8a346e4aae3597a4b6c824529725 (do not edit this line) */
