/* Generated By:JJTree: Do not edit this line. ASTRPredLevel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRPredLevel extends SimpleNode {
  public ASTRPredLevel(int id) {
    super(id);
  }

  public ASTRPredLevel(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd32eaf06ccc77e32714b5e9c5924a28 (do not edit this line) */
