/* Generated By:JJTree: Do not edit this line. ASTRPredLevel1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRPredLevel1 extends SimpleNode {
  public ASTRPredLevel1(int id) {
    super(id);
  }

  public ASTRPredLevel1(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f368638d781e3c92de4defbcfffda3d8 (do not edit this line) */
