/* Generated By:JJTree: Do not edit this line. ASTRElementImplementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRElementImplementation extends SimpleNode {
  public ASTRElementImplementation(int id) {
    super(id);
  }

  public ASTRElementImplementation(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ea36422844fc1ae92a704e1189e6860 (do not edit this line) */
