/* Generated By:JJTree: Do not edit this line. ASTResults.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTResults extends SimpleNode {
  public ASTResults(int id) {
    super(id);
  }

  public ASTResults(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c72a101e36ab06192e765b539ed65c1e (do not edit this line) */
