/* Generated By:JJTree: Do not edit this line. ASTRExpr0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExpr0 extends SimpleNode {
  public ASTRExpr0(int id) {
    super(id);
  }

  public ASTRExpr0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=932b5d28798d4253434d1f47590191e9 (do not edit this line) */
