/* Generated By:JJTree: Do not edit this line. ASTRExpr4.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExpr4 extends SimpleNode {
  public ASTRExpr4(int id) {
    super(id);
  }

  public ASTRExpr4(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f8434877ba3879f033eefca68c59f7f9 (do not edit this line) */
