/* Generated By:JJTree: Do not edit this line. ASTRCondition0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRCondition0 extends SimpleNode {
  public ASTRCondition0(int id) {
    super(id);
  }

  public ASTRCondition0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1df163d5656dfc4571e62bb619c7e570 (do not edit this line) */
