/* Generated By:JJTree: Do not edit this line. ASTRefinement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRefinement extends SimpleNode {
  public ASTRefinement(int id) {
    super(id);
  }

  public ASTRefinement(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1ec2c6bf6310c42a935d939ccc07eedb (do not edit this line) */
