/* Generated By:JJTree: Do not edit this line. ASTRSubstitutionMachine0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRSubstitutionMachine0 extends SimpleNode {
  public ASTRSubstitutionMachine0(int id) {
    super(id);
  }

  public ASTRSubstitutionMachine0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=48739a1119354de41325ca27a12809e1 (do not edit this line) */
