/* Generated By:JJTree: Do not edit this line. ASTRExprArith1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExprArith1 extends SimpleNode {
  public ASTRExprArith1(int id) {
    super(id);
  }

  public ASTRExprArith1(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90c3d91b17e4d830d9db3cd4a999d8ce (do not edit this line) */
