/* Generated By:JJTree: Do not edit this line. ASTRExprArith0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExprArith0 extends SimpleNode {
  public ASTRExprArith0(int id) {
    super(id);
  }

  public ASTRExprArith0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fcd3d29d97004bb15da15e4851118464 (do not edit this line) */
