/* Generated By:JJTree: Do not edit this line. ASTRExpr5.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExpr5 extends SimpleNode {
  public ASTRExpr5(int id) {
    super(id);
  }

  public ASTRExpr5(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79986e145d825bf60d6ea248be66931f (do not edit this line) */
