/* Generated By:JJTree: Do not edit this line. ASTRExpr1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExpr1 extends SimpleNode {
  public ASTRExpr1(int id) {
    super(id);
  }

  public ASTRExpr1(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=da2c3a83e56caa5f8e5c8b8a261bb000 (do not edit this line) */
