/* Generated By:JJTree: Do not edit this line. ASTRSubstitutionRefinement0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRSubstitutionRefinement0 extends SimpleNode {
  public ASTRSubstitutionRefinement0(int id) {
    super(id);
  }

  public ASTRSubstitutionRefinement0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bbb718bb9b7d852d31505c6213f563dc (do not edit this line) */
