/* Generated By:JJTree: Do not edit this line. ASTRPredLevel0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRPredLevel0 extends SimpleNode {
  public ASTRPredLevel0(int id) {
    super(id);
  }

  public ASTRPredLevel0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7bc2e0aab3a9ced415a2fc13299856fc (do not edit this line) */
