/* Generated By:JJTree: Do not edit this line. ASTRExpr6.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExpr6 extends SimpleNode {
  public ASTRExpr6(int id) {
    super(id);
  }

  public ASTRExpr6(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ad93c188711b248bab55d1daf4154303 (do not edit this line) */
