/* Generated By:JJTree: Do not edit this line. ASTRExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExpr extends SimpleNode {
  public ASTRExpr(int id) {
    super(id);
  }

  public ASTRExpr(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e34307c4bcda8c5ff51420a0c1824aa7 (do not edit this line) */
