/* Generated By:JJTree: Do not edit this line. ASTRUnionSetImplementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRUnionSetImplementation extends SimpleNode {
  public ASTRUnionSetImplementation(int id) {
    super(id);
  }

  public ASTRUnionSetImplementation(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b5a20e5e0b602c74978293af5cb1b8e (do not edit this line) */
