/* Generated By:JJTree: Do not edit this line. ASTRExprArith2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExprArith2 extends SimpleNode {
  public ASTRExprArith2(int id) {
    super(id);
  }

  public ASTRExprArith2(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=631fa0db0266ae52d9b89e37a8cee016 (do not edit this line) */
