/* Generated By:JJTree: Do not edit this line. ASTRefine.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRefine extends SimpleNode {
  public ASTRefine(int id) {
    super(id);
  }

  public ASTRefine(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02ba31246e2720673173122eb8c3809b (do not edit this line) */
