/* Generated By:JJTree: Do not edit this line. ASTRel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRel extends SimpleNode {
  public ASTRel(int id) {
    super(id);
  }

  public ASTRel(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=987348ba21b552a1dfff74bcef2304d3 (do not edit this line) */
