/* Generated By:JJTree: Do not edit this line. ASTRSubstitutionImplementation0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRSubstitutionImplementation0 extends SimpleNode {
  public ASTRSubstitutionImplementation0(int id) {
    super(id);
  }

  public ASTRSubstitutionImplementation0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=033ee3f466b70591df1dd1fbe3fa615d (do not edit this line) */
