/* Generated By:JJTree: Do not edit this line. ASTRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRange extends SimpleNode {
  public ASTRange(int id) {
    super(id);
  }

  public ASTRange(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c3463de8aea6365133bd144c0a6da26 (do not edit this line) */
