/* Generated By:JJTree: Do not edit this line. ASTRExpr3.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExpr3 extends SimpleNode {
  public ASTRExpr3(int id) {
    super(id);
  }

  public ASTRExpr3(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=29f7895dee0a041e499c6e038c8c2c3c (do not edit this line) */
