/* Generated By:JJTree: Do not edit this line. ASTRExpr2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRExpr2 extends SimpleNode {
  public ASTRExpr2(int id) {
    super(id);
  }

  public ASTRExpr2(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb4f7f157540d97320c56c63cef95bca (do not edit this line) */
