/* Generated By:JJTree: Do not edit this line. ASTRev.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTRev extends SimpleNode {
  public ASTRev(int id) {
    super(id);
  }

  public ASTRev(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f7877161434747fcbe6fb5e6efb4281f (do not edit this line) */
