/* Generated By:JJTree: Do not edit this line. ASTSubstitutionSetIn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionSetIn extends SimpleNode {
  public ASTSubstitutionSetIn(int id) {
    super(id);
  }

  public ASTSubstitutionSetIn(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2999676794248fa4a7668cddd1c7cfed (do not edit this line) */
