/* Generated By:JJTree: Do not edit this line. ASTSubstitutionChoice.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionChoice extends SimpleNode {
  public ASTSubstitutionChoice(int id) {
    super(id);
  }

  public ASTSubstitutionChoice(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2f780cad5e6a23bce76bcd16fb97e98 (do not edit this line) */
