/* Generated By:JJTree: Do not edit this line. ASTStringB.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTStringB extends SimpleNode {
  public ASTStringB(int id) {
    super(id);
  }

  public ASTStringB(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=afd9a9f878987328d0e57993d023cf5a (do not edit this line) */
