/* Generated By:JJTree: Do not edit this line. ASTSubstitutionVar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionVar extends SimpleNode {
  public ASTSubstitutionVar(int id) {
    super(id);
  }

  public ASTSubstitutionVar(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b6cb270220f9cea940c7d3a15bc30a2 (do not edit this line) */
