/* Generated By:JJTree: Do not edit this line. ASTSeq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSeq extends SimpleNode {
  public ASTSeq(int id) {
    super(id);
  }

  public ASTSeq(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=49204f377ef2c0f1303003b4b374eb86 (do not edit this line) */
