/* Generated By:JJTree: Do not edit this line. ASTSubstitutionCallOperation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionCallOperation extends SimpleNode {
  public ASTSubstitutionCallOperation(int id) {
    super(id);
  }

  public ASTSubstitutionCallOperation(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db89ba7be8749189bd75b0ea6c4dc0fd (do not edit this line) */
