/* Generated By:JJTree: Do not edit this line. ASTSubstitutionIf.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionIf extends SimpleNode {
  public ASTSubstitutionIf(int id) {
    super(id);
  }

  public ASTSubstitutionIf(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a808eda1c7768c9827eac3663a7cb6b (do not edit this line) */
