/* Generated By:JJTree: Do not edit this line. ASTSubstitutionAssertion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionAssertion extends SimpleNode {
  public ASTSubstitutionAssertion(int id) {
    super(id);
  }

  public ASTSubstitutionAssertion(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=000b342d5ef3917a677ffaff603e000a (do not edit this line) */
