/* Generated By:JJTree: Do not edit this line. ASTSubstitutionPrecondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionPrecondition extends SimpleNode {
  public ASTSubstitutionPrecondition(int id) {
    super(id);
  }

  public ASTSubstitutionPrecondition(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57aec2266579912374eab74953019a79 (do not edit this line) */
