/* Generated By:JJTree: Do not edit this line. ASTSubstitutionSkip.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionSkip extends SimpleNode {
  public ASTSubstitutionSkip(int id) {
    super(id);
  }

  public ASTSubstitutionSkip(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db053d78e6a64ad49f8121ff0f69915b (do not edit this line) */
