/* Generated By:JJTree: Do not edit this line. ASTSeq1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSeq1 extends SimpleNode {
  public ASTSeq1(int id) {
    super(id);
  }

  public ASTSeq1(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d26a05b4c683358c7dcbc3637b7ae98 (do not edit this line) */
