/* Generated By:JJTree: Do not edit this line. ASTSubstitutionSelect.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionSelect extends SimpleNode {
  public ASTSubstitutionSelect(int id) {
    super(id);
  }

  public ASTSubstitutionSelect(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=92986be8afd66bc49bfb79db68cdc613 (do not edit this line) */
