/* Generated By:JJTree: Do not edit this line. ASTSubstitutionBecomeSuch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionBecomeSuch extends SimpleNode {
  public ASTSubstitutionBecomeSuch(int id) {
    super(id);
  }

  public ASTSubstitutionBecomeSuch(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6f0f42cb3e758707139c91e0c879667 (do not edit this line) */
