/* Generated By:JJTree: Do not edit this line. ASTSubstitutionBecomeEqualFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionBecomeEqualFunction extends SimpleNode {
  public ASTSubstitutionBecomeEqualFunction(int id) {
    super(id);
  }

  public ASTSubstitutionBecomeEqualFunction(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50fa33691f1df97257ac78bd5b74f9f4 (do not edit this line) */
