/* Generated By:JJTree: Do not edit this line. ASTSees.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSees extends SimpleNode {
  public ASTSees(int id) {
    super(id);
  }

  public ASTSees(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b35fc0339d58f3d573d0dc0ab9aea581 (do not edit this line) */
