/* Generated By:JJTree: Do not edit this line. ASTSets.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSets extends SimpleNode {
  public ASTSets(int id) {
    super(id);
  }

  public ASTSets(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ece7ed9758bc08b995da8ed3fc134c8e (do not edit this line) */
