/* Generated By:JJTree: Do not edit this line. ASTSubstitutionMachine0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionMachine0 extends SimpleNode {
  public ASTSubstitutionMachine0(int id) {
    super(id);
  }

  public ASTSubstitutionMachine0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7612419c9d26ce5b1265958e47293c08 (do not edit this line) */
