/* Generated By:JJTree: Do not edit this line. ASTSubstitutionWhile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionWhile extends SimpleNode {
  public ASTSubstitutionWhile(int id) {
    super(id);
  }

  public ASTSubstitutionWhile(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=878afb4673e81e0a51e74af9c19bf595 (do not edit this line) */
