/* Generated By:JJTree: Do not edit this line. ASTSigma.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSigma extends SimpleNode {
  public ASTSigma(int id) {
    super(id);
  }

  public ASTSigma(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=198c757f0bb5de8c22d684e9d58f88f5 (do not edit this line) */
