/* Generated By:JJTree: Do not edit this line. ASTSubstitutionAny.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionAny extends SimpleNode {
  public ASTSubstitutionAny(int id) {
    super(id);
  }

  public ASTSubstitutionAny(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1cea7b9f74374eeef2920e3b68857ab (do not edit this line) */
