/* Generated By:JJTree: Do not edit this line. ASTSubstitutionCase.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionCase extends SimpleNode {
  public ASTSubstitutionCase(int id) {
    super(id);
  }

  public ASTSubstitutionCase(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e89b92954db85391df462595a029f4c8 (do not edit this line) */
