/* Generated By:JJTree: Do not edit this line. ASTSize.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSize extends SimpleNode {
  public ASTSize(int id) {
    super(id);
  }

  public ASTSize(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cae18d427a0c569dbb31d193a88b21e6 (do not edit this line) */
