/* Generated By:JJTree: Do not edit this line. ASTSucc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSucc extends SimpleNode {
  public ASTSucc(int id) {
    super(id);
  }

  public ASTSucc(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a849d149389c1f382ab27d2bbc362f9 (do not edit this line) */
