/* Generated By:JJTree: Do not edit this line. ASTSubstitutionImplementation0.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionImplementation0 extends SimpleNode {
  public ASTSubstitutionImplementation0(int id) {
    super(id);
  }

  public ASTSubstitutionImplementation0(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4c44b54374898dfe9a005677791042bf (do not edit this line) */
