/* Generated By:JJTree: Do not edit this line. ASTSubstitutionLet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTSubstitutionLet extends SimpleNode {
  public ASTSubstitutionLet(int id) {
    super(id);
  }

  public ASTSubstitutionLet(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf961e22f1a5f3058d9b123b294c1543 (do not edit this line) */
