/* Generated By:JJTree: Do not edit this line. ASTTail.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTTail extends SimpleNode {
  public ASTTail(int id) {
    super(id);
  }

  public ASTTail(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e1ceb630d42ea4e730e4cbbc7077d1dc (do not edit this line) */
