/* Generated By:JJTree: Do not edit this line. ASTThen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTThen extends SimpleNode {
  public ASTThen(int id) {
    super(id);
  }

  public ASTThen(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c137672d398bb6f56e9bbc9c6b10ae9 (do not edit this line) */
