/* Generated By:JJTree: Do not edit this line. ASTUnionSetImplementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTUnionSetImplementation extends SimpleNode {
  public ASTUnionSetImplementation(int id) {
    super(id);
  }

  public ASTUnionSetImplementation(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a5a7b26a5fefeb8d9dd0835a890a5f9 (do not edit this line) */
