/* Generated By:JJTree: Do not edit this line. ASTUnionGeneralized.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTUnionGeneralized extends SimpleNode {
  public ASTUnionGeneralized(int id) {
    super(id);
  }

  public ASTUnionGeneralized(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=45ca7f9e0db7cdb8c5e0ac68885ec9fd (do not edit this line) */
