/* Generated By:JJTree: Do not edit this line. ASTValues.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTValues extends SimpleNode {
  public ASTValues(int id) {
    super(id);
  }

  public ASTValues(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3ca88a690e943c166ee95514c8d0450 (do not edit this line) */
