/* Generated By:JJTree: Do not edit this line. ASTWhen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.grammaire;

public
class ASTWhen extends SimpleNode {
  public ASTWhen(int id) {
    super(id);
  }

  public ASTWhen(BParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4117abffb07dfbb2ee032646401b3559 (do not edit this line) */
