/* Generated By:JavaCC: Do not edit this line. BParserTreeConstants.java Version 5.0 */
package parser.grammaire;

public interface BParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTMACHINE = 2;
  public int JJTREFINEMENT = 3;
  public int JJTIMPLEMENTATION = 4;
  public int JJTHEADER = 5;
  public int JJTNAME = 6;
  public int JJTPARAMETERS = 7;
  public int JJTREFINE = 8;
  public int JJTDEFINITIONS = 9;
  public int JJTDEFINITION = 10;
  public int JJTSUBSTITUTIONCALLOPERATION = 11;
  public int JJTCONSTRAINTS = 12;
  public int JJTSEES = 13;
  public int JJTIMPORTS = 14;
  public int JJTDECLARATION = 15;
  public int JJTINCLUDES = 16;
  public int JJTSETS = 17;
  public int JJTCONCRETECONSTANTS = 18;
  public int JJTABSTRACTCONSTANTS = 19;
  public int JJTPROPERTIES = 20;
  public int JJTVALUES = 21;
  public int JJTVALUE = 22;
  public int JJTCONCRETEVARIABLES = 23;
  public int JJTABSTRACTVARIABLES = 24;
  public int JJTINVARIANT = 25;
  public int JJTASSERTIONS = 26;
  public int JJTINITIALISATION = 27;
  public int JJTOPERATIONS = 28;
  public int JJTOPERATION = 29;
  public int JJTRESULTS = 30;
  public int JJTSUBSTITUTIONMACHINE0 = 31;
  public int JJTRSUBSTITUTIONMACHINE0 = 32;
  public int JJTSUBSTITUTIONREFINEMENT0 = 33;
  public int JJTRSUBSTITUTIONREFINEMENT0 = 34;
  public int JJTSUBSTITUTIONIMPLEMENTATION0 = 35;
  public int JJTRSUBSTITUTIONIMPLEMENTATION0 = 36;
  public int JJTSUBSTITUTIONPRECONDITION = 37;
  public int JJTSUBSTITUTIONBEGIN = 38;
  public int JJTSUBSTITUTIONSKIP = 39;
  public int JJTIDENTIFIERS = 40;
  public int JJTSUBSTITUTIONBECOMEEQUALVARIABLES = 41;
  public int JJTSUBSTITUTIONBECOMEEQUALFUNCTION = 42;
  public int JJTLEFTCALLFUNCTION = 43;
  public int JJTSUBSTITUTIONBECOMESUCH = 44;
  public int JJTSUBSTITUTIONSETIN = 45;
  public int JJTSUBSTITUTIONCASE = 46;
  public int JJTEITHER = 47;
  public int JJTOR = 48;
  public int JJTSUBSTITUTIONASSERTION = 49;
  public int JJTSUBSTITUTIONCHOICE = 50;
  public int JJTSUBSTITUTIONIF = 51;
  public int JJTELSEIF = 52;
  public int JJTSUBSTITUTIONSELECT = 53;
  public int JJTWHEN = 54;
  public int JJTSUBSTITUTIONANY = 55;
  public int JJTSUBSTITUTIONLET = 56;
  public int JJTLISTTERMES = 57;
  public int JJTELSE = 58;
  public int JJTTHEN = 59;
  public int JJTLETDEFINITIONS = 60;
  public int JJTEQUAL = 61;
  public int JJTSUBSTITUTIONVAR = 62;
  public int JJTARRAYELEMENT = 63;
  public int JJTINDEXOFELEMENT = 64;
  public int JJTRINDEXOFELEMENT = 65;
  public int JJTLISTETERMESTRING = 66;
  public int JJTSUBSTITUTIONWHILE = 67;
  public int JJTCONDITION0 = 68;
  public int JJTRCONDITION0 = 69;
  public int JJTNOT = 70;
  public int JJTPREDICATEPARENTHESIS = 71;
  public int JJTCONDITION2 = 72;
  public int JJTCALLINTERME = 73;
  public int JJTUNIONSETIMPLEMENTATION = 74;
  public int JJTRUNIONSETIMPLEMENTATION = 75;
  public int JJTELEMENTUNIONSETIMPLEMENTATION = 76;
  public int JJTRELEMENTIMPLEMENTATION = 77;
  public int JJTEXTENSIONSET = 78;
  public int JJTLISTEXPRESSION = 79;
  public int JJTELEMENTIMPLEMENTATION = 80;
  public int JJTNATRANGE = 81;
  public int JJTEXPRARITH = 82;
  public int JJTREXPRARITH = 83;
  public int JJTEXPRARITH0 = 84;
  public int JJTREXPRARITH0 = 85;
  public int JJTEXPRARITH1 = 86;
  public int JJTREXPRARITH1 = 87;
  public int JJTEXPRARITH2 = 88;
  public int JJTREXPRARITH2 = 89;
  public int JJTEXPRESSIONPARENTHESIS = 90;
  public int JJTSUCC = 91;
  public int JJTPRED = 92;
  public int JJTCONDITIONEXPRESSION = 93;
  public int JJTPREDLEVEL = 94;
  public int JJTRPREDLEVEL = 95;
  public int JJTPREDLEVEL0 = 96;
  public int JJTRPREDLEVEL0 = 97;
  public int JJTPREDLEVEL1 = 98;
  public int JJTRPREDLEVEL1 = 99;
  public int JJTFORALL = 100;
  public int JJTIMPLICATION = 101;
  public int JJTEXISTS = 102;
  public int JJTPREDLEVEL3 = 103;
  public int JJTEXPR = 104;
  public int JJTREXPR = 105;
  public int JJTEXPR0 = 106;
  public int JJTREXPR0 = 107;
  public int JJTEXPR1 = 108;
  public int JJTREXPR1 = 109;
  public int JJTEXPR2 = 110;
  public int JJTREXPR2 = 111;
  public int JJTEXPR3 = 112;
  public int JJTREXPR3 = 113;
  public int JJTEXPR4 = 114;
  public int JJTREXPR4 = 115;
  public int JJTEXPR5 = 116;
  public int JJTREXPR5 = 117;
  public int JJTEXPR6 = 118;
  public int JJTREXPR6 = 119;
  public int JJTEXPR7 = 120;
  public int JJTINVERSE = 121;
  public int JJTIMAGE = 122;
  public int JJTCALLFUNCTION = 123;
  public int JJTPREDICATEEXPRESSION = 124;
  public int JJTEMPTYSEQUENCE = 125;
  public int JJTEXTENSIONSEQUENCE = 126;
  public int JJTSIGMA = 127;
  public int JJTPI = 128;
  public int JJTUNIONQUANTIFIED = 129;
  public int JJTINTERSECTIONQUANTIFIED = 130;
  public int JJTLAMBDA = 131;
  public int JJTUNIONGENERALIZED = 132;
  public int JJTINTERSECTIONGENERALIZED = 133;
  public int JJTINTEGERSET = 134;
  public int JJTINTEGER = 135;
  public int JJTBOOLEAN = 136;
  public int JJTBOOLEANSET = 137;
  public int JJTSTRING = 138;
  public int JJTSTRINGB = 139;
  public int JJTMAX = 140;
  public int JJTMIN = 141;
  public int JJTCARD = 142;
  public int JJTPOWERSET = 143;
  public int JJTNONEMPTYSUBSETS = 144;
  public int JJTFINITEPOWERSET = 145;
  public int JJTNONEMPTYFINITESUBSETS = 146;
  public int JJTIDENTITY = 147;
  public int JJTPRJ1 = 148;
  public int JJTPRJ2 = 149;
  public int JJTITERATE = 150;
  public int JJTCLOSURE = 151;
  public int JJTCLOSURE1 = 152;
  public int JJTDOMAIN = 153;
  public int JJTRANGE = 154;
  public int JJTFNC = 155;
  public int JJTREL = 156;
  public int JJTSEQ = 157;
  public int JJTSEQ1 = 158;
  public int JJTISEQ = 159;
  public int JJTISEQ1 = 160;
  public int JJTPERM = 161;
  public int JJTSIZE = 162;
  public int JJTFIRST = 163;
  public int JJTLAST = 164;
  public int JJTFRONT = 165;
  public int JJTTAIL = 166;
  public int JJTREV = 167;
  public int JJTCONC = 168;
  public int JJTDOLLARZERO = 169;
  public int JJTEMPTYSET = 170;
  public int JJTCOMPREHENSIONSET = 171;
  public int JJTLISTIDENT = 172;
  public int JJTLISTPARAMETRESDEFS = 173;
  public int JJTCALLDEFINITIONSUBSTITUTION = 174;
  public int JJTCALLDEFINITIONPREDICATE = 175;
  public int JJTCALLDEFINITIONLISTEXPRESSION = 176;
  public int JJTCALLDEFINITIONEXPRESSION = 177;
  public int JJTIDENTIFIER = 178;
  public int JJTIDENTIFIERCOMPOSED = 179;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Machine",
    "Refinement",
    "Implementation",
    "Header",
    "Name",
    "Parameters",
    "Refine",
    "Definitions",
    "Definition",
    "SubstitutionCallOperation",
    "Constraints",
    "Sees",
    "Imports",
    "Declaration",
    "Includes",
    "Sets",
    "ConcreteConstants",
    "AbstractConstants",
    "Properties",
    "Values",
    "Value",
    "ConcreteVariables",
    "AbstractVariables",
    "Invariant",
    "Assertions",
    "Initialisation",
    "Operations",
    "Operation",
    "Results",
    "SubstitutionMachine0",
    "RSubstitutionMachine0",
    "SubstitutionRefinement0",
    "RSubstitutionRefinement0",
    "SubstitutionImplementation0",
    "RSubstitutionImplementation0",
    "SubstitutionPrecondition",
    "SubstitutionBegin",
    "SubstitutionSkip",
    "Identifiers",
    "SubstitutionBecomeEqualVariables",
    "SubstitutionBecomeEqualFunction",
    "LeftCallFunction",
    "SubstitutionBecomeSuch",
    "SubstitutionSetIn",
    "SubstitutionCase",
    "Either",
    "Or",
    "SubstitutionAssertion",
    "SubstitutionChoice",
    "SubstitutionIf",
    "ElseIf",
    "SubstitutionSelect",
    "When",
    "SubstitutionAny",
    "SubstitutionLet",
    "ListTermes",
    "Else",
    "Then",
    "LetDefinitions",
    "Equal",
    "SubstitutionVar",
    "ArrayElement",
    "IndexOfElement",
    "RIndexOfElement",
    "ListeTermeString",
    "SubstitutionWhile",
    "Condition0",
    "RCondition0",
    "Not",
    "PredicateParenthesis",
    "Condition2",
    "CallInTerme",
    "UnionSetImplementation",
    "RUnionSetImplementation",
    "ElementUnionSetImplementation",
    "RElementImplementation",
    "ExtensionSet",
    "ListExpression",
    "ElementImplementation",
    "NatRange",
    "ExprArith",
    "RExprArith",
    "ExprArith0",
    "RExprArith0",
    "ExprArith1",
    "RExprArith1",
    "ExprArith2",
    "RExprArith2",
    "ExpressionParenthesis",
    "Succ",
    "Pred",
    "ConditionExpression",
    "PredLevel",
    "RPredLevel",
    "PredLevel0",
    "RPredLevel0",
    "PredLevel1",
    "RPredLevel1",
    "ForAll",
    "Implication",
    "Exists",
    "PredLevel3",
    "Expr",
    "RExpr",
    "Expr0",
    "RExpr0",
    "Expr1",
    "RExpr1",
    "Expr2",
    "RExpr2",
    "Expr3",
    "RExpr3",
    "Expr4",
    "RExpr4",
    "Expr5",
    "RExpr5",
    "Expr6",
    "RExpr6",
    "Expr7",
    "Inverse",
    "Image",
    "CallFunction",
    "PredicateExpression",
    "EmptySequence",
    "ExtensionSequence",
    "Sigma",
    "Pi",
    "UnionQuantified",
    "IntersectionQuantified",
    "Lambda",
    "UnionGeneralized",
    "IntersectionGeneralized",
    "IntegerSet",
    "Integer",
    "Boolean",
    "BooleanSet",
    "STRING",
    "StringB",
    "Max",
    "Min",
    "Card",
    "PowerSet",
    "NonEmptySubsets",
    "FinitePowerSet",
    "NonEmptyFiniteSubsets",
    "Identity",
    "Prj1",
    "Prj2",
    "Iterate",
    "Closure",
    "Closure1",
    "Domain",
    "Range",
    "Fnc",
    "Rel",
    "Seq",
    "Seq1",
    "Iseq",
    "Iseq1",
    "Perm",
    "Size",
    "First",
    "Last",
    "Front",
    "Tail",
    "Rev",
    "Conc",
    "DollarZero",
    "EmptySet",
    "ComprehensionSet",
    "ListIdent",
    "ListParametresDefs",
    "CallDefinitionSubstitution",
    "CallDefinitionPredicate",
    "CallDefinitionListExpression",
    "CallDefinitionExpression",
    "Identifier",
    "IdentifierComposed",
  };
}
/* JavaCC - OriginalChecksum=a1ae6aaebad546107a01afe167cc5dba (do not edit this line) */
