/* Generated By:JJTree&JavaCC: Do not edit this line. BParserConstants.java */
/*****************************************************************************
*
* (C) 2003  B. TATIBOUET - Université de Franche-Comté
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
******************************************************************************/

package parser.grammaire;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Machine = 5;
  /** RegularExpression Id. */
  int End = 6;
  /** RegularExpression Id. */
  int Sets = 7;
  /** RegularExpression Id. */
  int Invariant = 8;
  /** RegularExpression Id. */
  int Variables = 9;
  /** RegularExpression Id. */
  int Operations = 10;
  /** RegularExpression Id. */
  int Events = 11;
  /** RegularExpression Id. */
  int Constraints = 12;
  /** RegularExpression Id. */
  int Sees = 13;
  /** RegularExpression Id. */
  int Constants = 14;
  /** RegularExpression Id. */
  int Properties = 15;
  /** RegularExpression Id. */
  int Includes = 16;
  /** RegularExpression Id. */
  int ConcreteVariables = 17;
  /** RegularExpression Id. */
  int AbstractVariables = 18;
  /** RegularExpression Id. */
  int ConcreteConstants = 19;
  /** RegularExpression Id. */
  int AbstractConstants = 20;
  /** RegularExpression Id. */
  int Assertions = 21;
  /** RegularExpression Id. */
  int Initialisation = 22;
  /** RegularExpression Id. */
  int Refinement = 23;
  /** RegularExpression Id. */
  int Refines = 24;
  /** RegularExpression Id. */
  int Implementation = 25;
  /** RegularExpression Id. */
  int Imports = 26;
  /** RegularExpression Id. */
  int Definitions = 27;
  /** RegularExpression Id. */
  int Values = 28;
  /** RegularExpression Id. */
  int Begin = 29;
  /** RegularExpression Id. */
  int Pre = 30;
  /** RegularExpression Id. */
  int If = 31;
  /** RegularExpression Id. */
  int Then = 32;
  /** RegularExpression Id. */
  int Elsif = 33;
  /** RegularExpression Id. */
  int Else = 34;
  /** RegularExpression Id. */
  int Assert = 35;
  /** RegularExpression Id. */
  int Any = 36;
  /** RegularExpression Id. */
  int Where = 37;
  /** RegularExpression Id. */
  int Let = 38;
  /** RegularExpression Id. */
  int Be = 39;
  /** RegularExpression Id. */
  int InLetVar = 40;
  /** RegularExpression Id. */
  int Choice = 41;
  /** RegularExpression Id. */
  int OrC = 42;
  /** RegularExpression Id. */
  int Select = 43;
  /** RegularExpression Id. */
  int When = 44;
  /** RegularExpression Id. */
  int Case = 45;
  /** RegularExpression Id. */
  int Of = 46;
  /** RegularExpression Id. */
  int Either = 47;
  /** RegularExpression Id. */
  int Var = 48;
  /** RegularExpression Id. */
  int While = 49;
  /** RegularExpression Id. */
  int Do = 50;
  /** RegularExpression Id. */
  int Variant = 51;
  /** RegularExpression Id. */
  int EmptySet = 52;
  /** RegularExpression Id. */
  int EmptySequence = 53;
  /** RegularExpression Id. */
  int EmptySequenceOld = 54;
  /** RegularExpression Id. */
  int Equivalence = 55;
  /** RegularExpression Id. */
  int Subset = 56;
  /** RegularExpression Id. */
  int NotSubset = 57;
  /** RegularExpression Id. */
  int Implication = 58;
  /** RegularExpression Id. */
  int StrictSubset = 59;
  /** RegularExpression Id. */
  int NotStrictSubset = 60;
  /** RegularExpression Id. */
  int NotSetMemberShip = 61;
  /** RegularExpression Id. */
  int NotEqual = 62;
  /** RegularExpression Id. */
  int LessThanOrEqual = 63;
  /** RegularExpression Id. */
  int GreatherThanOrEqual = 64;
  /** RegularExpression Id. */
  int Relation = 65;
  /** RegularExpression Id. */
  int PartialSurjection = 66;
  /** RegularExpression Id. */
  int PartialFunction = 67;
  /** RegularExpression Id. */
  int TotalSurjection = 68;
  /** RegularExpression Id. */
  int TotalFunction = 69;
  /** RegularExpression Id. */
  int PartialBijection = 70;
  /** RegularExpression Id. */
  int PartialInjection = 71;
  /** RegularExpression Id. */
  int TotalBijection = 72;
  /** RegularExpression Id. */
  int TotalInjection = 73;
  /** RegularExpression Id. */
  int OperationReturn = 74;
  /** RegularExpression Id. */
  int DevientEgal = 75;
  /** RegularExpression Id. */
  int OpenCurly = 76;
  /** RegularExpression Id. */
  int CloseCurly = 77;
  /** RegularExpression Id. */
  int Maplet = 78;
  /** RegularExpression Id. */
  int DomainSubstraction = 79;
  /** RegularExpression Id. */
  int DomainRestriction = 80;
  /** RegularExpression Id. */
  int RangeSubstraction = 81;
  /** RegularExpression Id. */
  int RangeRestriction = 82;
  /** RegularExpression Id. */
  int Override = 83;
  /** RegularExpression Id. */
  int DirectProduct = 84;
  /** RegularExpression Id. */
  int PrependSequence = 85;
  /** RegularExpression Id. */
  int AppendSequence = 86;
  /** RegularExpression Id. */
  int PrefixSequence = 87;
  /** RegularExpression Id. */
  int SuffixSequence = 88;
  /** RegularExpression Id. */
  int SetIn = 89;
  /** RegularExpression Id. */
  int EqualEqual = 90;
  /** RegularExpression Id. */
  int NatRange = 91;
  /** RegularExpression Id. */
  int Power = 92;
  /** RegularExpression Id. */
  int Union = 93;
  /** RegularExpression Id. */
  int Intersection = 94;
  /** RegularExpression Id. */
  int Lambda = 95;
  /** RegularExpression Id. */
  int SuchAs = 96;
  /** RegularExpression Id. */
  int Forall = 97;
  /** RegularExpression Id. */
  int Exists = 98;
  /** RegularExpression Id. */
  int Tilde = 99;
  /** RegularExpression Id. */
  int OpenBraces = 100;
  /** RegularExpression Id. */
  int CloseBraces = 101;
  /** RegularExpression Id. */
  int Point = 102;
  /** RegularExpression Id. */
  int OpenParen = 103;
  /** RegularExpression Id. */
  int CloseParen = 104;
  /** RegularExpression Id. */
  int Comma = 105;
  /** RegularExpression Id. */
  int Or = 106;
  /** RegularExpression Id. */
  int And = 107;
  /** RegularExpression Id. */
  int Not = 108;
  /** RegularExpression Id. */
  int Skip = 109;
  /** RegularExpression Id. */
  int Minus = 110;
  /** RegularExpression Id. */
  int Plus = 111;
  /** RegularExpression Id. */
  int Product = 112;
  /** RegularExpression Id. */
  int Division = 113;
  /** RegularExpression Id. */
  int Modulo = 114;
  /** RegularExpression Id. */
  int Equal = 115;
  /** RegularExpression Id. */
  int ConcatSequence = 116;
  /** RegularExpression Id. */
  int LessThan = 117;
  /** RegularExpression Id. */
  int GreatherThan = 118;
  /** RegularExpression Id. */
  int In = 119;
  /** RegularExpression Id. */
  int DollarZero = 120;
  /** RegularExpression Id. */
  int Composition = 121;
  /** RegularExpression Id. */
  int ParallelProduct = 122;
  /** RegularExpression Id. */
  int SetMinus = 123;
  /** RegularExpression Id. */
  int CartesianProduct = 124;
  /** RegularExpression Id. */
  int Parallel = 125;
  /** RegularExpression Id. */
  int SemiColon = 126;
  /** RegularExpression Id. */
  int Prj1 = 127;
  /** RegularExpression Id. */
  int Prj2 = 128;
  /** RegularExpression Id. */
  int POW = 129;
  /** RegularExpression Id. */
  int FIN = 130;
  /** RegularExpression Id. */
  int POW1 = 131;
  /** RegularExpression Id. */
  int FIN1 = 132;
  /** RegularExpression Id. */
  int InterGen = 133;
  /** RegularExpression Id. */
  int UnionGen = 134;
  /** RegularExpression Id. */
  int UnionQuant = 135;
  /** RegularExpression Id. */
  int InterQuant = 136;
  /** RegularExpression Id. */
  int Id = 137;
  /** RegularExpression Id. */
  int Dom = 138;
  /** RegularExpression Id. */
  int Ran = 139;
  /** RegularExpression Id. */
  int Iterate = 140;
  /** RegularExpression Id. */
  int Closure = 141;
  /** RegularExpression Id. */
  int Closure1 = 142;
  /** RegularExpression Id. */
  int Card = 143;
  /** RegularExpression Id. */
  int Max = 144;
  /** RegularExpression Id. */
  int Min = 145;
  /** RegularExpression Id. */
  int Succ = 146;
  /** RegularExpression Id. */
  int Pred = 147;
  /** RegularExpression Id. */
  int Sigma = 148;
  /** RegularExpression Id. */
  int Pi = 149;
  /** RegularExpression Id. */
  int Seq = 150;
  /** RegularExpression Id. */
  int Iseq = 151;
  /** RegularExpression Id. */
  int Seq1 = 152;
  /** RegularExpression Id. */
  int Iseq1 = 153;
  /** RegularExpression Id. */
  int Perm = 154;
  /** RegularExpression Id. */
  int Conc = 155;
  /** RegularExpression Id. */
  int Front = 156;
  /** RegularExpression Id. */
  int Tail = 157;
  /** RegularExpression Id. */
  int First = 158;
  /** RegularExpression Id. */
  int Last = 159;
  /** RegularExpression Id. */
  int Size = 160;
  /** RegularExpression Id. */
  int Rev = 161;
  /** RegularExpression Id. */
  int Fnc = 162;
  /** RegularExpression Id. */
  int Rel = 163;
  /** RegularExpression Id. */
  int Bool = 164;
  /** RegularExpression Id. */
  int Nat = 165;
  /** RegularExpression Id. */
  int Nat1 = 166;
  /** RegularExpression Id. */
  int Natural = 167;
  /** RegularExpression Id. */
  int Natural1 = 168;
  /** RegularExpression Id. */
  int Int = 169;
  /** RegularExpression Id. */
  int Integer = 170;
  /** RegularExpression Id. */
  int True = 171;
  /** RegularExpression Id. */
  int False = 172;
  /** RegularExpression Id. */
  int Boolean = 173;
  /** RegularExpression Id. */
  int StringSet = 174;
  /** RegularExpression Id. */
  int MaxInt = 175;
  /** RegularExpression Id. */
  int MinInt = 176;
  /** RegularExpression Id. */
  int IDENTIFIER = 177;
  /** RegularExpression Id. */
  int String = 178;
  /** RegularExpression Id. */
  int Number = 179;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 4>",
    "\"MACHINE\"",
    "\"END\"",
    "\"SETS\"",
    "\"INVARIANT\"",
    "\"VARIABLES\"",
    "\"OPERATIONS\"",
    "\"EVENTS\"",
    "\"CONSTRAINTS\"",
    "\"SEES\"",
    "\"CONSTANTS\"",
    "\"PROPERTIES\"",
    "\"INCLUDES\"",
    "\"CONCRETE_VARIABLES\"",
    "\"ABSTRACT_VARIABLES\"",
    "\"CONCRETE_CONSTANTS\"",
    "\"ABSTRACT_CONSTANTS\"",
    "\"ASSERTIONS\"",
    "\"INITIALISATION\"",
    "\"REFINEMENT\"",
    "\"REFINES\"",
    "\"IMPLEMENTATION\"",
    "\"IMPORTS\"",
    "\"DEFINITIONS\"",
    "\"VALUES\"",
    "\"BEGIN\"",
    "\"PRE\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSIF\"",
    "\"ELSE\"",
    "\"ASSERT\"",
    "\"ANY\"",
    "\"WHERE\"",
    "\"LET\"",
    "\"BE\"",
    "\"IN\"",
    "\"CHOICE\"",
    "\"OR\"",
    "\"SELECT\"",
    "\"WHEN\"",
    "\"CASE\"",
    "\"OF\"",
    "\"EITHER\"",
    "\"VAR\"",
    "\"WHILE\"",
    "\"DO\"",
    "\"VARIANT\"",
    "<EmptySet>",
    "<EmptySequence>",
    "\"<>\"",
    "\"<=>\"",
    "\"<:\"",
    "\"/<:\"",
    "\"=>\"",
    "\"<<:\"",
    "\"/<<:\"",
    "\"/:\"",
    "\"/=\"",
    "\"<=\"",
    "\">=\"",
    "\"<->\"",
    "\"+->>\"",
    "\"+->\"",
    "\"-->>\"",
    "\"-->\"",
    "\">+>>\"",
    "\">+>\"",
    "\">->>\"",
    "\">->\"",
    "\"<--\"",
    "\":=\"",
    "\"[\"",
    "\"]\"",
    "\"|->\"",
    "\"<<|\"",
    "\"<|\"",
    "\"|>>\"",
    "\"|>\"",
    "\"<+\"",
    "\"><\"",
    "\"->\"",
    "\"<-\"",
    "\"/|\\\\\"",
    "\"\\\\|/\"",
    "\"::\"",
    "\"==\"",
    "\"..\"",
    "\"**\"",
    "\"\\\\/\"",
    "\"/\\\\\"",
    "\"%\"",
    "\"|\"",
    "\"!\"",
    "\"#\"",
    "\"~\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"or\"",
    "\"&\"",
    "\"not\"",
    "\"skip\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "\"=\"",
    "\"^\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\"$0\"",
    "\"\\u00b0\"",
    "\"//\"",
    "\"\\\\\"",
    "\"\\u20ac\"",
    "\"||\"",
    "\";\"",
    "\"prj1\"",
    "\"prj2\"",
    "\"POW\"",
    "\"FIN\"",
    "\"POW1\"",
    "\"FIN1\"",
    "\"inter\"",
    "\"union\"",
    "\"UNION\"",
    "\"INTER\"",
    "\"id\"",
    "\"dom\"",
    "\"ran\"",
    "\"iterate\"",
    "\"closure\"",
    "\"closure1\"",
    "\"card\"",
    "\"max\"",
    "\"min\"",
    "\"succ\"",
    "\"pred\"",
    "\"SIGMA\"",
    "\"PI\"",
    "\"seq\"",
    "\"iseq\"",
    "\"seq1\"",
    "\"iseq1\"",
    "\"perm\"",
    "\"conc\"",
    "\"front\"",
    "\"tail\"",
    "\"first\"",
    "\"last\"",
    "\"size\"",
    "\"rev\"",
    "\"fnc\"",
    "\"rel\"",
    "\"bool\"",
    "\"NAT\"",
    "\"NAT1\"",
    "\"NATURAL\"",
    "\"NATURAL1\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"BOOL\"",
    "\"STRING\"",
    "\"MAXINT\"",
    "\"MININT\"",
    "<IDENTIFIER>",
    "<String>",
    "<Number>",
  };

}
